# Site Settings
lang: en-US
title: Kolmar Kafran
email: kolmar@kafran.net
description: "Filling the void."
url: "https://kafran.net" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "kafran/kafran.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
# Site Author
author:
  name: "Kolmar Kafran" # "Your Name"
  picture: "/assets/images/bio.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
#twitter_username: kafran
github_username: kafran
linkedin_username: kolmar-kafran
stackoverflow_username: 3147247
devto_username: kafran
logo: /assets/icons/icon.svg
#google_analytics:
#disqus:
#  shortname: basically-basic-theme
search: false
search_full_content: true
#search_provider: lunr
#algolia:
#  application_id: # YOUR_APPLICATION_ID
#  index_name: # YOUR_INDEX_NAME
#  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
#  powered_by: # true (default), false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false
remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: "America/Sao_Paulo" # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Jekyll Feed
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - "_portfolio"


# Collections
# collections:
#   portfolio:
#     output: true
#     permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "about.md"
      type: pages
    values:
      layout: about
      read_time: false
  #_portfolio
  # - scope:
  #     path: "_portfolio"
  #     type: portfolio
  #   values:
  #     layout: post
  #     read_time: true
